[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startupProbe = "curl -f http://localhost:8080/ || exit 1"
startupProbeTimeout = 120

[service]
internal_port = 8080
auto_deploy = true

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"] 