[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startupProbe = "curl -f http://localhost:8080/ || exit 1"
startupProbeTimeout = 120 